//----------------------------------------------------------------------
//	Copyright (C) 2010 Matias N. Goldberg ("dark_sylinc")
//  This file is part of Ogre Meshy.
//
//  Ogre Meshy is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  Ogre Meshy is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with Ogre Meshy.  If not, see <http://www.gnu.org/licenses/>.
//----------------------------------------------------------------------

#ifndef __GridSettingsImpl__
#define __GridSettingsImpl__

/**
@file
Subclass of GridSettings, which is generated by wxFormBuilder.
*/

#include "wxOgreMeshViewerMainFrame.h"

//// end generated include

/** Implementing GridSettings */
class GridSettingsImpl : public GridSettings
{
	double				m_cellSize;
	double				m_cellWidth;
	double				m_cellDepth;

	protected:
		// Handlers for GridSettings events.
		void OnPresetsChange( wxCommandEvent& event );
		void OnCommitChanges( wxCommandEvent& event );
	public:
		/** Constructor */
		GridSettingsImpl( wxWindow* parent, float cellSize, float cellWidth, float cellDepth );
	//// end generated class members

		float getCellSize()  const { return static_cast<float>(m_cellSize); }
		float getCellWidth() const { return static_cast<float>(m_cellWidth); }
		float getCellDepth() const { return static_cast<float>(m_cellDepth); }
	
};

#endif // __GridSettingsImpl__
